name: Publish pre Release package version

on: 
  push:
    branches:
      - next
  
jobs:
  commit: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 16
      - run: git config user.name "$GITHUB_ACTOR"
      - run: git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
      - run: npm version prerelease --preid=next -m "Release %s"
      - run: VERSION=$(node -p "require('./package.json').version")
      - run: git push "https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/$GITHUB_REPOSITORY.git" 


  publish-npm:
    needs: commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run deploy:next
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
