name: Publish pre Release package version

on: 
  push:
    branches:
      - next
  
jobs:
  commit: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with: 
          node-version: 16
      - run: npm version prerelease --preid=next
      
      - uses: EndBug/add-and-commit@v9
        with: 
          default_author: github_actor
          add: .
          message: 'Update package version'


  publish-npm:
    needs: commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run deploy
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}